version: '2'

services:

  # dummydb:
  #   build:
  #     context: ../../
  #     dockerfile: docker/dummydb/Dockerfile
  #   ports:
  #     - "1984:1984"
  #   networks:
  #     main:
  #       aliases:
  #         - dummydb

  explorer:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/explorer/Dockerfile
    volumes:
      - ../../../explorer-data/target:/build_docker/target
    ports:
      - "5000:5000"
    networks:
      main:
        ipv4_address: 10.5.0.5
        aliases:
          - explorer
    depends_on:
      # - bitcoin
      - elements
      - postgres

  elements:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/daemon/elements.docker
    volumes:
      - ../../../explorer-data/elementsregtest:/build_docker/.elements
      - ../../../explorer-data/elementsparent:/build_docker/.elementsparent
      - ../../../explorer-data/elementside:/build_docker/.elementside
    networks:
      main:
        aliases:
          - elements

  # bitcoin:
  #   build:
  #     context: ../../
  #     args:
  #       - ENV_NAME
  #     dockerfile: docker/daemon/bitcoin.docker
  #   volumes:
  #     - ../../../explorer-data/bitcoin:/build_docker/.bitcoin
  #     - ../../../explorer-data/testnet3:/build_docker/.testnet3
  #     - ../../../explorer-data/regtest:/build_docker/.regtest
  #   networks:
  #     main:
  #       aliases:
  #         - bitcoin

  data:
    restart: "no"
    image: postgres:9.6
    volumes:
      - ../../../explorer-data/db/postgresql:/var/lib/postgresql/data
    command: "true"

  postgres:
    restart: "always"
    image: postgres:9.6
    volumes_from:
      - data
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - postgresalias

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
