version: '2'

services:

  explorer:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/explorer/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/target:/build_docker/target
      - /tmp/test-elements-explorer/keys:/build_docker/keys
    ports:
      - "5000:5000"
    networks:
      main:
        ipv4_address: 10.5.0.5
        aliases:
          - explorer
    depends_on:
      - bitcoin
      - elements
      - postgres

  elements:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/daemon/elements.docker
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/elementsregtest:/build_docker/.elements
    networks:
      main:
        aliases:
          - elements

  bitcoin:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/daemon/bitcoin.docker
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/regtest:/build_docker/.regtest
    networks:
      main:
        aliases:
          - bitcoin

  data:
    restart: "no"
    image: postgres:9.6
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/db/postgresql:/var/lib/postgresql/data
    command: bash -c "chown -R $$(id -u) /var/lib/postgresql/data"

  postgres:
    restart: "always"
    image: postgres:9.6
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes_from:
      - data
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - postgresalias

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
