version: '3.6'

services:

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - explorer

  explorer:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/explorer/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/target:/build_docker/target
      - /tmp/test-elements-explorer/keys:/build_docker/keys
    ports:
      - "5000:5000"
    links:
      - postgres
      - daemons

  daemons:
    build:
      context: ../../
      args:
        - ENV_NAME
        - CORE_DAEMON_NAME
        - ELEMENTS_DAEMON_NAME
        - SIGNET_DAEMON_NAME
      dockerfile: docker/daemon/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/elementsregtest:/build_docker/.elements
      - /tmp/test-elements-explorer/regtest:/build_docker/.regtest

  data:
    restart: "no"
    image: postgres:9.6
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/db/postgresql:/var/lib/postgresql/data
    command: bash -c "chown -R $$(id -u) /var/lib/postgresql/data"

  postgres:
    restart: "always"
    image: postgres:9.6
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/db/postgresql:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
