web: gunicorn py:app -b "$WEB_HOST:$WEB_PORT" -w $WEB_WORKERS -k gevent --log-config py/config/logging.conf

# create_db: python lib/explorer/bin/create_db.py --address $DB_PROXY_ADR --dbaddress $DB_BACKEND_ADR --dbtype $DB_PROXY_TYPE --schema $MINQL_SCHEMA --dbname $DB_NAME --dbuser $DB_USER --dbpass $DB_PASS

subscriber_bitcoin: python lib/explorer/bin/chain_subscriber.py --chain bitcoin
subscriber_testnet3: python lib/explorer/bin/chain_subscriber.py --chain testnet3
subscriber_elementsregtest: python lib/explorer/bin/chain_subscriber.py --chain elementsregtest
