version: '3.6'

services:

  explorer:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/explorer/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/target:/build_docker/target
      - /tmp/test-elements-explorer/keys:/build_docker/keys
    ports:
      - "5000:5000"
    links:
      - daemons
      - dummydb

  daemons:
    build:
      context: ../../
      args:
        - ENV_NAME
        - CORE_DAEMON_NAME
        - ELEMENTS_DAEMON_NAME
        - SIGNET_DAEMON_NAME
      dockerfile: docker/daemon/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/elementsregtest:/build_docker/.elements
      - /tmp/test-elements-explorer/regtest:/build_docker/.regtest

  dummydb:
    build:
      context: ../../
      dockerfile: docker/dummydb/Dockerfile
