version: '2'

services:

  explorer:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/explorer/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/target:/build_docker/target
      - /tmp/test-elements-explorer/keys:/build_docker/keys
    ports:
      - "5000:5000"
    networks:
      main:
        ipv4_address: 10.5.0.5
        aliases:
          - explorer
    depends_on:
      - daemons
      - dummydb

  daemons:
    build:
      context: ../../
      args:
        - ENV_NAME
        - CORE_DAEMON_NAME
        - ELEMENTS_DAEMON_NAME
      dockerfile: docker/daemon/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/elementsregtest:/build_docker/.elements
      - /tmp/test-elements-explorer/regtest:/build_docker/.regtest
    networks:
      main:
        aliases:
          - daemons

  dummydb:
    build:
      context: ../../
      dockerfile: docker/dummydb/Dockerfile
    networks:
      main:
        aliases:
          - dummydb

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
