version: '2'

services:

  explorer:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/explorer/Dockerfile
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/target:/build_docker/target
      - /tmp/test-elements-explorer/keys:/build_docker/keys
    ports:
      - "5000:5000"
    networks:
      main:
        ipv4_address: 10.5.0.5
        aliases:
          - explorer
    depends_on:
      - bitcoin
      - elements
      - dummydb

  elements:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/daemon/elements.docker
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/elementsregtest:/build_docker/.elements
    networks:
      main:
        aliases:
          - elements

  bitcoin:
    build:
      context: ../../
      args:
        - ENV_NAME
      dockerfile: docker/daemon/bitcoin.docker
    environment:
      - CURRENT_UID
    user: ${CURRENT_UID}
    volumes:
      - /tmp/test-elements-explorer/regtest:/build_docker/.regtest
    networks:
      main:
        aliases:
          - bitcoin

  dummydb:
    build:
      context: ../../
      dockerfile: docker/dummydb/Dockerfile
    networks:
      main:
        aliases:
          - dummydb

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
