
bitcoin: ./$BITCOIN_BRANCH_DIR/src/bitcoind -conf=/build_docker/daemon-conf/bitcoin.conf -datadir=/build_docker/.bitcoin/

testnet3: ./$BITCOIN_BRANCH_DIR/src/bitcoind -conf=/build_docker/daemon-conf/testnet3.conf -datadir=/build_docker/.testnet3/

regtest: ./$BITCOIN_BRANCH_DIR/src/bitcoind -conf=/build_docker/daemon-conf/regtest.conf -datadir=/build_docker/.regtest/

signet: ./$SIGNET_BRANCH_DIR/src/bitcoind -conf=/build_docker/daemon-conf/signet.conf -datadir=/build_docker/.signet/

elementsparent: ./$ELEMENTS_BRANCH_DIR/src/elementsd -conf=/build_docker/daemon-conf/elementsparent.conf -datadir=/build_docker/.elementsparent/

elementsregtest: sleep 1 ; ./$ELEMENTS_BRANCH_DIR/src/elementsd -conf=/build_docker/daemon-conf/elementsregtest.conf -datadir=/build_docker/.elements/

elementside: sleep 1 ; ./$ELEMENTS_BRANCH_DIR/src/elementsd -conf=/build_docker/daemon-conf/elementside.conf -datadir=/build_docker/.elementside/

signetside: sleep 1 ; ./$ELEMENTS_BRANCH_DIR/src/elementsd -conf=/build_docker/daemon-conf/signetside.conf -datadir=/build_docker/.signetside/
